service: dispatcher

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: "arn:aws:sqs:us-east-1:*:*"
functions:
  source:
    handler: src/handler.source
    events:
      - schedule: rate(1 minute)
    environment:
      AWS_SQS_DISPATCHER_URL: ${env:AWS_SQS_DISPATCHER_URL}
      AWS_SQS_BROWSER_URL: ${env:AWS_SQS_BROWSER_URL}
  spread:
    handler: src/handler.spread
    events:
     - sqs:
        arn: ${env:AWS_SQS_DISPATCHER_ARN}
        batchSize: 1
    environment:
      AWS_SQS_DISPATCHER_URL: ${env:AWS_SQS_DISPATCHER_URL}
      AWS_SQS_BROWSER_URL: ${env:AWS_SQS_BROWSER_URL}